<a href="https://colab.research.google.com/github/kenta1114/Machine-Learning/blob/main/Numpy_concat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
l=np.array([1,1,5,2,4])
np.diff(l)

array([ 0,  4, -3,  2])

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [5]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[10, 20], [30, 40]])

In [6]:
np.concatenate([c, d], axis=1)

array([[ 1,  2,  3, 10, 20],
       [ 4,  5,  6, 30, 40]])

In [9]:
e = np.array([[1, 2, 3], [4, 5, 6]])
f = np.array([[10, 20, 30], [40, 50, 60]])

In [10]:
np.vstack([e,f])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [11]:
a = np.array([[1, 2, 10], [3, 4, 20], [5, 6, 30], [7, 8, 40]])

In [12]:
col1, col2 = np.hsplit(a, [2])

In [13]:
col1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
col2

array([[10],
       [20],
       [30],
       [40]])

In [15]:
row1,row2=np.vsplit(a,[2])

In [16]:
row1

array([[ 1,  2, 10],
       [ 3,  4, 20]])

In [17]:
row2

array([[ 5,  6, 30],
       [ 7,  8, 40]])

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
a = np.array([1, 2, 3])

In [20]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [21]:
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [22]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7])

In [23]:
xx, yy = np.meshgrid(x, y)

In [24]:
xx

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [25]:
yy

array([[5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])